M

diff --git a/roles/rabbitmq/tasks/main.yml b/roles/rabbitmq/tasks/main.yml
--- a/roles/rabbitmq/tasks/main.yml
+++ b/roles/rabbitmq/tasks/main.yml
@@ -1,3 +1,74 @@
-- name: print rabbitmq
-  debug:
-    msg: rabbitmq
+# source common.sh
+
+# roboshop_app_password=$1
+
+# if [ -z "${1}" ]; then
+#   echo -e "\e[31mMissing Roboshop App User passowrd argument\e[om"
+#   exit 1
+# fi
+
+# print_head "setup Erlang repos"
+# curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash &>>${log_file}
+# status_check $?
+
+# print_head "Setup RabbitMQ Repos"
+# curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>${log_file}
+# status_check $?
+
+# print_head "Install Erlang & RabbitMQ"
+# yum install rabbitmq-server erlang -y  &>>${log_file}
+# status_check $?
+
+# print_head "Enable RabbitMQ Service"
+# systemctl enable rabbitmq-server  &>>${log_file}
+# status_check $?
+
+# print_head "Start RabbitMQ Service"
+# systemctl start rabbitmq-server  &>>${log_file}
+# status_check $?
+
+# print_head "Add Application User"
+# rabbitmqctl list_users | grep roboshop &>>${log_file}
+# if [ $? -ne 0 ]; then
+#  rabbitmqctl add_user roboshop ${roboshop_app_password} &>>${log_file}
+# fi
+# status_check $?
+
+# ## roboshop123 password --------
+
+# print_head "Configuration Permission for App User"
+# rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"  &>>${log_file}
+# # status_check $?
+
+
+- name: Setupt Erlang Repos
+  ansible.builtin.shell: curl -s  https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
+
+
+- name: Install rabitmq Repos
+  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
+
+
+- name: Install Erlang and rabitmq
+  ansible.builtin.yum:
+    - rabbitmq-server
+    - erlang
+  start: installed
+
+
+- name: start Rabbitmq service
+  ansible.builtin.systemd:
+  name: rabbitmq-server
+  state: started
+  enabled: yes
+
+
+- name: Add appliaction User
+  community.rabbitmq.rabbitmq_user:
+    user: roboshop
+    password: roboshop123
+    vhost: /
+    configure_priv: .*
+    read_priv: .*
+    write_priv: .*
+    state: present
